# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "rabbitizer" = super.buildPythonPackage rec {
    pname = "rabbitizer";
    version = "1.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2c/d2/01847a840e323bdb29c6a29742f9751871f92a9bcff77e69035c9fb33592/rabbitizer-1.12.0.tar.gz";
      sha256 = "02zy7j0ny9x1q32sykxrgxx6mzknrzhj0zvly2y58f0k6jprn36v";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "spimdisasm" = super.buildPythonPackage rec {
    pname = "spimdisasm";
    version = "1.30.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/dc/b8d7b340c2ed25dda0e9857bbcf663b2e658cd694f36e77d123b7701d77f/spimdisasm-1.30.2-py3-none-any.whl";
      sha256 = "0rdmy2582mb7kz1l0fs94ls6p98jvqis81akkzaanr7vic9cmahh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."rabbitizer"
    ];
  };
}
