# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "rabbitizer" = super.buildPythonPackage rec {
    pname = "rabbitizer";
    version = "1.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/d8/1aa8aac857f5fac9baf19230621a831bac0cad93ff85d7fb14d36f855e64/rabbitizer-1.13.0.tar.gz";
      sha256 = "09vipv91wx2p0gzyyv9chz0wxchcncg42dla98vh0bb8s4s0q6a4";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "spimdisasm" = super.buildPythonPackage rec {
    pname = "spimdisasm";
    version = "1.34.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/00/9e6ade58804312a2406d5e8b81d3124c327cfcd527d83b631a0c54982333/spimdisasm-1.34.2-py3-none-any.whl";
      sha256 = "06wm4l2qn34yp0d1cw55vjssffsrp6lsz3n7zc0vmnhmjm31iy12";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."rabbitizer"
    ];
  };
}
