# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "rabbitizer" = super.buildPythonPackage rec {
    pname = "rabbitizer";
    version = "1.7.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/08/4dbc9b5df75e20dd0aa2e529c2139c9e79de5255ba0b60b1726572a8988b/rabbitizer-1.7.6.tar.gz";
      sha256 = "02yshfc869miar1llw23jqnvjy1plcgv87k4a782a9m6s7dawxa3";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "spimdisasm" = super.buildPythonPackage rec {
    pname = "spimdisasm";
    version = "1.16.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/3f/03754f4db3a13fe8795525eaf4fcdf77d24226597de4215c2d4483a455ff/spimdisasm-1.16.4-py3-none-any.whl";
      sha256 = "0vrwy27cmz3mz2r74ybln565g003bv7qja3nb1g1npyhvwc6kw7r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."rabbitizer"
    ];
  };
}
